### PR TITLE
feat: updated a few things

### PR DESCRIPTION
**Pull request by raphael-arce**
- ~~disable renovate by default~~ <- not anymore, we've decided to enable/disable renovate via the renovate github app, 
- remove vscode settings folder, 
- add .idea folder to gitignore, 
- updated readme
- updated default workflow

### CODE REVIEW

**Comment by ff6347** [comment]
I am not a fan of this decision, since the opt in is harder for users then the opt out. But, hey, not my business anymore 😏. But shouldn't the README tell, in the section about renovate, that it needs to be enabled if desired? @raphael-arce

**Comment by ff6347** [comment]
If needed disable renovate here. https://github.com/technologiestiftung/renovate-config/blob/master/default.json

**Comment by raphael-arce** [comment]
@ff6347 Yes, there is this line in the readme: https://github.com/technologiestiftung/template-repo-citylab/pull/19/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R18
or do you mean something else?

As most of the devs in the TSB complain about renovate and are not necessarily familiar with it (e.g. know how to disable it), I think it's more pragmatic to disable by default, but when needed/enabled, use the same rules as before.

**Comment by raphael-arce** [comment]
I know what you mean, but I don't intend to disable Renovate globally. The goal is for future projects created from this template to have the flexibility to enable it when needed, by simply setting `"enabled": true` in the `.github/renovate.json` file 👍

**Review by aeschi — APPROVED** [review]
LGTM! 👍

**Comment by ff6347** [comment]
But then renovate will be active on repos that don't use this template

**Comment by raphael-arce** [comment]
@ff6347 that's a fair point. We've discussed it a bit with the team and the opinions were that it'd be easier/better to handle enabling/disabling renovate by selecting repositories manually in the renovate github app. I've removed the relevant line in the `renovate.json` 👍

**Comment by ff6347** [comment]
@raphael-arce this sounds a little like moving away from renovate. The can everybody change the settings of the GitHub App? Will anyone think of renovate when it is not active by default? I know the little bot can be annoying at times but better then dependencies rotting away. 😄

**Pull request merged**
